name: Run Flask App in Codespaces

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Define the service for port forwarding
      codespaces:
        image: ghcr.io/github/vscode-codespaces:latest
        ports:
          - 5000:5000  # Map port 5000 in Codespaces to 5000 locally

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r ./D3js_Flask/requirements.txt

      - name: Start Flask App
        run: python ./D3js_Flask/app.py

      # Optional: Wait for the app to start before proceeding
      - name: Wait for Flask App to Start
        run: sleep 5

      # Optional: Open a browser tab to the running app in Code Spaces
      - name: Open App in Browser
        run: open http://localhost:5000  # Change the port if needed
